### ISSUE TITLE
Appreciate some pointers on how to make this work with JSX components

### ISSUE THREAD

**Issue by Vincent-liuwingsang** [baileyherbert/reflection#4]
hey there, I'm trying to generate property documentation on arbitrary JSX component (in typescript).
Any idea on how this can be achieved with this library?

I'm assuming this information is accessible at least by eslint/vscode as it warns you when you're missing a property when initiating a component.

**Comment by baileyherbert** [comment]
Unfortunately, this package won't be sufficient for your needs. It's only designed for runtime reflection (by analyzing prototype chains and decorator metadata), so it can't read your source code or see any types except what the TypeScript compiler emits.

React components are generally functions, with their props passed as a single object parameter. In that case, TypeScript will sadly emit a generic `Object` type for the parameter. Therefore, this package won't be able to analyze the properties, nor can it analyze the component to begin with, because only class reflection is supported.

Class components can be analyzed by the package to some extent. It will see their hierarchies, fields, as well as methods (including private and inherited ones e.g. from `React.Component`) and basic information about their parameters (with only primitive types, if any at all). However, class component props are typed using a generic `<T>`, and TypeScript does not emit metadata for those, so this package can't see them.

So as far as I know, it's not possible to enumerate or get any information about props for a React component, regardless of how it was written.

To my knowledge, VSCode and ESLint launch a dedicated language server (tsserver) that parses your raw source code and provides a syntax tree (AST) for type checking and detailed code analysis. Most likely, you will want to hook into this or do the same, depending on how your project executes.

You might find success using the [`typescript` API](https://github.com/Microsoft/TypeScript/wiki/Using-the-Compiler-API), which can read your code and supposedly allows you to directly interact with the AST. That would allow you to operate at the same level of detail as VSCode and ESLint, but will be much more sophisticated.
